    
---
- hosts: docker-host
  become: true
  tasks:
    - name: remove docker images
      shell: docker image rm -f dineshk2508/ci_cd_ansible_docker_hub_versioning:latest
       
    - name: create docker image
      shell: docker run -d -p 8093:8080 dineshk2508/ci_cd_ansible_docker_hub_versioning:latest
