    
---
- hosts: web-servers
  become: true
  tasks:
    - name: remove docker images
      shell: docker image rm -f dineshk2508/ci_cd_versioning_ad:latest
       
    - name: create docker image
      shell: docker run -d --name webapp -p 8090:8080 dineshk2508/ci_cd_versioning_ad:latest
